# Generated by Django 4.0.7 on 2022-09-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('adID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Ad',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('adID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.ads')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
