# Generated by Django 4.0.7 on 2022-09-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carID', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('number_plate', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerID', models.AutoField(primary_key=True, serialize=False)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
    ]
